// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	contact "zero-chat/user/api/internal/handler/contact"
	user "zero-chat/user/api/internal/handler/user"
	"zero-chat/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reg",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/get",
					Handler: contact.GetContactHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: contact.AddContactHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/del",
					Handler: contact.DelContactHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/search",
					Handler: contact.SearchContactHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/search/user",
					Handler: contact.SearchUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/user"),
	)
}
