// Code generated by goctl. DO NOT EDIT.
package types

type TokenReply struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	Uid          string `json:"uid"`
}

type User struct {
	Id       int64  `json:"id,optional"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	TokenReply
}

type SearchUserReq struct {
	Uid string `json:"uid"`
}

type SearchUserResp struct {
	User
}

type SearchContactReq struct {
	Key string `json:"key"`
}

type SearchContactResp struct {
	List []*User `json:"list"`
}

type GetContactResp struct {
	List []*User `json:"list"`
}

type AddContactReq struct {
	Uid string `json:"uid"`
}

type DelContactReq struct {
	Uid string `json:"uid"`
}
