// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chat "zero-chat/api/internal/handler/chat"
	user "zero-chat/api/internal/handler/user"
	"zero-chat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reg",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/send",
					Handler: chat.SendMsgHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chat",
					Handler: chat.ChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cao",
					Handler: chat.CaoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/chat"),
	)
}
