// Code generated by goctl. DO NOT EDIT.
package types

type Message struct {
	Msg string `json:"msg"`
	T   int64  `json:"t"`
}

type MessageInfo struct {
	ToUid   int64  `json:"to_uid"`
	ToUser  string `json:"to_user"`
	LastMsg string `json:"last_msg"`
}

type GetAllChatResp struct {
	List []*MessageInfo `json:"list"`
}

type GetChatHistoryReq struct {
	ToUid int64 `json:"to_uid"`
}

type GetChatHistoryResp struct {
	List []*Message `json:"list"`
}

type SendMsgReq struct {
	Msg string `json:"msg"`
	Uid string `json:"uid"`
}

type SendMsgResp struct {
}
